Contact section
olawale-o/portfolio-mobile-version pull request #6
Opened 2021-06-08 15:58 UTC by olawale-o

2021-06-08 19:08 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__This is a brilliant effort from you guys. You've really done an amazing job so far. In this PR, here are my major highlights:__

- Correct configuration of linters with no errors reported :100: 
- Descriptive PR title, summary and commit messages :+1: 

__However, you need to make some required changes before moving on to the next assignment. Please check my comments below and fix them as appropriate.__

### **Required Changes** :recycle: 
Check the comments under the review.

### **Optional Changes** :zap: 
N/A


* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can be notified about your comments and respond._

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *

_Reviewed by:_ [**Taofeek Olalere**](https://github.com/teekaytech)
__Cheers & Happy coding :smiley:__

2021-06-08 19:08 UTC, teekaytech commented on style.css
> +}
As I've mentioned earlier, you guys have done an amazing job. Your contact form works well and the UI is great :muscle: 

I realized that you've used the `Grid` layout style for this section. The grid layout works fine and it's acceptable. However, this project specifically stated that you should use CSS Flexbox layout. It is important we always stick to the project specification. Therefore, I suggest you replace the grid layout with flexbox.

2021-06-09 02:47 UTC, MahmoudBakr23 approved these changes
Hello Team, @olawale-o @hiromataba😃,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 02:47 UTC, MahmoudBakr23 commented on index.html
> +                    value="Olawale"
- [ ] **OPTIONAL** I suggest deleting the `value` attribute and just leave the `placeholder`

2021-06-09 02:47 UTC, MahmoudBakr23 commented on index.html
> +                    value="olawale@micoverse.org"
- [ ] **OPTIONAL** I suggest deleting the `value` attribute and just leave the `placeholder`

2021-06-09 02:49 UTC, merged